---
# tasks file for manager
- name: Init a new swarm with default parameters
  community.docker.docker_swarm:
    state: present
  register: swarm_info # this is to set some info we can call to later on