---
# tasks file for worker

- name: print join token
  debug:
    msg: "{{ hostvars['swarm-manager']['swarm_info']['swarm_facts']['JoinTokens']['Worker'] }}"

- name: Add nodes
  community.docker.docker_swarm:
    state: join
    advertise_addr: "{{ inventory_hostname }}" # name of host running on
    join_token: "{{ hostvars['swarm-manager']['swarm_info']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: [ 'swarm-manager:2377' ] # name of manager