---
# tasks file for docker

- name: 'update and upgrade apt'
  apt:
    upgrade: true
    update_cache: true

- name: 'Install requirements'
  apt:
    pkg:
    - python3
    - python3-pip
    - git
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    state: latest
    update_cache: true

- name: 'Add gpg key'
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  
- name: 'Add apt repo'
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename|lower }} stable
    
- name: 'Install docker community edition'
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: latest
    update_cache: true
  
- name: 'Install docker'
  pip:
    name: docker
  register: docker_info

- name: 'Install JSONdiff and pyyaml'
  pip:
    name: 
    - jsondiff
    - pyyaml